---
title: "Analiza wydajności struktur pamięciowych baz danych"
author: "Mikołaj Mierzejewski, Kamil Osak, Filip Szóstak"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    theme: spacelab
    number_sections: yes
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set( echo  = FALSE)
library(dplyr)
library(ggplot2)
library(plotly)
```


```{r init, echo=FALSE}
draw_chart <- function(operation) {
  data <- read.csv(paste("out/", operation, ".csv", sep=""), header=FALSE, col.names=c("database", "time", "size"))
  df <- data %>%
    mutate(database=factor(database, labels=c('Dictionary', 'List', 'T-Tree')), time=time/1000, size=size/1000) %>%
    group_by(database, size) %>%
    summarize(time=mean(time))
  
  return(
    ggplot(df, aes(x=size, y=time, color=database, fill=database, shape=database)) + 
      geom_point() + 
      geom_smooth(formula = y ~ x, method = 'lm') + 
      labs(
        x="Database size [thousands of records]", 
        color="", 
        fillz="", 
        y="Operation time [s]", 
        title=paste("Memory structure effeciency for", operation, "operation.")) + 
      scale_y_continuous(trans='log10') + 
      scale_fill_discrete(name="Memory structure type:") +
      scale_color_discrete(name="Memory structure type:") +
      scale_shape_discrete(name="Memory structure type:")
   )
    
}
```

# Abstract

# Wprowadzenie

## Motywacje i opis problemu

## Wybrane struktury pamięciowe 

## Cel pracy 

# Metodologia badań

## Przeprowadzone badania 

## Opis środowiska

# Wyniki badań

## Dodawanie danych
```{r create}
ggplotly(draw_chart("create"))
```

## Odczyt losowy danych
```{r read}
ggplotly(draw_chart("read"))
```

## Odczyt sekwencyjny danych
```{r read_range}
ggplotly(draw_chart("read_range"))
```

## Aktualizacja danych
```{r update}
ggplotly(draw_chart("update"))
```

## Usuwanie danych
```{r delete}
ggplotly(draw_chart("delete"))
```

# Zakończenie

## Podsumowanie prac

## Dalszy kierunek rozwoju

# Literatura

